package agent

import (
	"context"
	"fmt"
	"strings"
	"sync"
	"time"

	"github.com/block-p/liara-helper-agent/internal/agent/tools"
	"github.com/block-p/liara-helper-agent/internal/rag"
	"github.com/block-p/liara-helper-agent/pkg/llm"
)

// AgenticResponse represents the rich response generated by the agent.
type AgenticResponse struct {
	Answer          string          `json:"answer"`
	ToolExecuted    string          `json:"tool_executed,omitempty"`
	Sources         []rag.DocSource `json:"sources,omitempty"`
	SuggestedNext   []string        `json:"suggested_next,omitempty"`
	Duration        time.Duration   `json:"duration_ms"`
}

// Agent coordinates RAG, tools, and multi-turn conversation sessions.
type Agent struct {
	RAGEngine      *rag.Engine
	SessionManager *SessionManager
	Tools          map[string]tools.Tool
	temperature    float32
	mu             sync.RWMutex
}

// NewAgent creates a new Agent instance with registered tools.
func NewAgent(ragEngine *rag.Engine, sm *SessionManager) *Agent {
	if sm == nil {
		sm = NewSessionManager(20)
	}

	configTool := tools.NewConfigGeneratorTool()
	logTool := tools.NewErrorLogAnalyzerTool()

	toolsMap := map[string]tools.Tool{
		configTool.Name(): configTool,
		logTool.Name():    logTool,
	}

	return &Agent{
		RAGEngine:      ragEngine,
		SessionManager: sm,
		Tools:          toolsMap,
		temperature:    0.3,
	}
}

// SetTemperature updates the model creativity temperature safely.
func (a *Agent) SetTemperature(t float32) {
	a.mu.Lock()
	defer a.mu.Unlock()
	if t < 0.0 {
		t = 0.0
	}
	if t > 1.0 {
		t = 1.0
	}
	a.temperature = t
}

// GetTemperature retrieves the current model creativity temperature safely.
func (a *Agent) GetTemperature() float32 {
	a.mu.RLock()
	defer a.mu.RUnlock()
	if a.temperature <= 0 {
		return 0.3
	}
	return a.temperature
}

// ProcessMessage handles an incoming user message within a session.
func (a *Agent) ProcessMessage(ctx context.Context, sessionID, userMessage string) (*AgenticResponse, error) {
	return a.ProcessMessageStream(ctx, sessionID, userMessage, nil)
}

// ProcessMessageStream processes an incoming user message, optionally streaming tokens via onToken.
func (a *Agent) ProcessMessageStream(ctx context.Context, sessionID, userMessage string, onToken func(string) error) (*AgenticResponse, error) {
	startTime := time.Now()
	trimmed := strings.TrimSpace(userMessage)

	// Fetch previous session history BEFORE adding the current message
	history := a.SessionManager.GetHistory(sessionID)

	// Add current user message to session history
	a.SessionManager.AddMessage(sessionID, llm.ChatMessage{
		Role:    "user",
		Content: trimmed,
	})

	// 1. Fast Greeting / Chit-Chat Intent Detection (Zero RAG Token Consumption)
	if isGreeting(trimmed) {
		greetingAnswer := "سلام و درود! من دستیار هوشمند و متخصص فنی پلتفرم ابری **لیارا** هستم.\n\n" +
			"چطور می‌توانم در زمینه استقرار برنامه‌ها، دیتابیس‌ها، تنظیم فایل‌های کانفیگ (`liara.json` یا `Dockerfile`) و رفع خطاهای دیپلوی کمکتان کنم؟"

		if onToken != nil {
			_ = onToken(greetingAnswer)
		}

		resp := &AgenticResponse{
			Answer: greetingAnswer,
			SuggestedNext: []string{
				"نحوه استقرار برنامه Node.js در لیارا",
				"ساخت فایل کانفیگ liara.json",
				"راهنمای اتصال به دیتابیس PostgreSQL",
				"تحلیل و رفع خطای 502 Bad Gateway",
			},
			Duration: time.Since(startTime),
		}
		a.SessionManager.AddMessage(sessionID, llm.ChatMessage{Role: "assistant", Content: greetingAnswer})
		return resp, nil
	}

	// 2. Thanks / Farewell Intent Detection
	if isThanksOrFarewell(trimmed) {
		farewellAnswer := "خواهش می‌کنم! خوشحالم که توانستم کمکتان کنم. هر زمان سوال دیگری درباره لیارا یا خطاهای دیپلوی داشتید در خدمتم."
		if onToken != nil {
			_ = onToken(farewellAnswer)
		}

		resp := &AgenticResponse{
			Answer:   farewellAnswer,
			Duration: time.Since(startTime),
		}
		a.SessionManager.AddMessage(sessionID, llm.ChatMessage{Role: "assistant", Content: farewellAnswer})
		return resp, nil
	}

	// 3. Error Log Debugging Intent
	if isErrorLogInput(trimmed) {
		logTool := a.Tools["analyze_error_log"]
		result, err := logTool.Execute(ctx, trimmed)
		if err == nil && result.Success {
			if onToken != nil {
				_ = onToken(result.Data)
			}

			resp := &AgenticResponse{
				Answer:       result.Data,
				ToolExecuted: logTool.Name(),
				SuggestedNext: []string{
					"مشاهده لاگ‌های زنده با دستور liara logs",
					"بررسی وضعیت برنامه با دستور liara status",
					"تست اجرای برنامه در محیط لوکال با Docker",
				},
				Duration: time.Since(startTime),
			}
			a.SessionManager.AddMessage(sessionID, llm.ChatMessage{Role: "assistant", Content: result.Data})
			return resp, nil
		}
	}

	// 4. Config Generation Intent
	if platform, isConfigReq := detectConfigRequest(trimmed); isConfigReq {
		configTool := a.Tools["generate_liara_config"]
		result, err := configTool.Execute(ctx, fmt.Sprintf(`{"platform": "%s"}`, platform))
		if err == nil && result.Success {
			if onToken != nil {
				_ = onToken(result.Data)
			}

			resp := &AgenticResponse{
				Answer:       result.Data,
				ToolExecuted: configTool.Name(),
				SuggestedNext: []string{
					"ساخت برنامه در کنسول لیارا",
					"تنظیم متغیرهای محیطی با دستور liara env:set",
					"استقرار نهایی با دستور liara deploy",
				},
				Duration: time.Since(startTime),
			}
			a.SessionManager.AddMessage(sessionID, llm.ChatMessage{Role: "assistant", Content: result.Data})
			return resp, nil
		}
	}

	// 5. Standard & Hybrid RAG Query with Conversational Memory
	searchQuery := synthesizeSearchQuery(trimmed, history)

	ragResp, err := a.RAGEngine.QueryStream(ctx, searchQuery, rag.QueryOptions{
		TopK:        4,
		History:     history,
		Temperature: a.GetTemperature(),
	}, onToken)
	if err != nil {
		return nil, err
	}

	// Proactively generate next steps based on query content
	suggestedSteps := generateNextSteps(trimmed, ragResp.Answer)

	resp := &AgenticResponse{
		Answer:        ragResp.Answer,
		Sources:       ragResp.Sources,
		SuggestedNext: suggestedSteps,
		Duration:      time.Since(startTime),
	}

	a.SessionManager.AddMessage(sessionID, llm.ChatMessage{
		Role:    "assistant",
		Content: ragResp.Answer,
	})

	return resp, nil
}

// isGreeting detects standard greetings and chit-chat in Persian and English
func isGreeting(text string) bool {
	clean := strings.ToLower(strings.TrimSpace(text))
	clean = strings.Trim(clean, "!?.، ")

	greetings := []string{
		"سلام", "سلام علیکم", "درود", "درود بر شما", "صبح بخیر", "عصر بخیر", "شب بخیر",
		"روز بخیر", "وقت بخیر", "چطوری", "خوبی", "احوالت", "hi", "hello", "hey", "sup",
	}

	for _, g := range greetings {
		if clean == g {
			return true
		}
	}

	// Prefix check for greetings with polite extensions (e.g. "سلام خسته نباشید")
	if strings.HasPrefix(clean, "سلام ") || strings.HasPrefix(clean, "درود ") {
		// Only consider greeting if short (less than 6 words)
		if len(strings.Fields(clean)) <= 5 {
			return true
		}
	}

	return false
}

// isThanksOrFarewell detects thanks and goodbyes
func isThanksOrFarewell(text string) bool {
	clean := strings.ToLower(strings.TrimSpace(text))
	clean = strings.Trim(clean, "!?.، ")

	phrases := []string{
		"ممنون", "مرسی", "متشکرم", "خیلی ممنون", "دمت گرم", "دستت درد نکنه", "دستت طلا",
		"سپاس", "سپاسگزارم", "خداحافظ", "فعلا", "خسته نباشید", "bye", "goodbye", "thanks", "thank you",
	}

	for _, p := range phrases {
		if clean == p {
			return true
		}
	}

	if len(strings.Fields(clean)) <= 4 && (strings.Contains(clean, "ممنون") || strings.Contains(clean, "مرسی") || strings.Contains(clean, "دمت گرم")) {
		return true
	}

	return false
}

// synthesizeSearchQuery improves vector retrieval for short contextual follow-up questions
func synthesizeSearchQuery(currentQuery string, history []llm.ChatMessage) string {
	clean := strings.TrimSpace(currentQuery)
	words := strings.Fields(clean)

	// If query is short (e.g. "حالا چطور بهش وصل شم؟", "کانفیگش چطوره؟") and history exists
	if len(words) <= 7 && len(history) > 0 {
		var lastUserQuery string
		for i := len(history) - 1; i >= 0; i-- {
			if history[i].Role == "user" {
				lastUserQuery = history[i].Content
				break
			}
		}

		if lastUserQuery != "" && !isGreeting(lastUserQuery) {
			// Extract possible keywords from last turn to enrich search
			return clean + " " + lastUserQuery
		}
	}

	return clean
}

// Helper heuristics for intent detection
func isErrorLogInput(text string) bool {
	lower := strings.ToLower(text)
	indicators := []string{
		"error:", "err!", "fatal:", "exception in thread", "traceback (most recent call last)",
		"econnrefused", "502 bad gateway", "504 gateway time-out", "exit status 1",
		"modulenotfounderror", "npm err!", "yarn run v", "standard_init_linux.go",
	}
	for _, ind := range indicators {
		if strings.Contains(lower, ind) {
			return true
		}
	}
	return false
}

func detectConfigRequest(text string) (string, bool) {
	lower := strings.ToLower(text)
	if strings.Contains(lower, "liara.json") || strings.Contains(lower, "فایل کانفیگ") || strings.Contains(lower, "کانفیگ برای") || strings.Contains(lower, "config for") {
		platforms := []string{"node", "next", "python", "django", "flask", "fastapi", "go", "php", "laravel", "docker", "static", "wordpress"}
		for _, p := range platforms {
			if strings.Contains(lower, p) {
				return p, true
			}
		}
		return "node", true
	}
	return "", false
}

func generateNextSteps(question, answer string) []string {
	combined := strings.ToLower(question + " " + answer)
	var steps []string

	// 1. Error resolution follow-ups
	if strings.Contains(combined, "502") || strings.Contains(combined, "bad gateway") {
		steps = append(steps, "تنظیم پورت صحیح در فایل liara.json")
		steps = append(steps, "بررسی گوش دادن برنامه روی 0.0.0.0 به جای 127.0.0.1")
		steps = append(steps, "مشاهده لاگ‌های زنده با دستور: liara logs")
		return steps
	}
	if strings.Contains(combined, "out of memory") || strings.Contains(combined, "heap") || strings.Contains(combined, "oom") {
		steps = append(steps, "ارتقای پلن رم برنامه در پنل لیارا")
		steps = append(steps, "تنظیم فلگ بهینه‌سازی حافظه در دستور build")
		steps = append(steps, "بررسی مصرف رم با دستور: liara status")
		return steps
	}
	if strings.Contains(combined, "econnrefused") || strings.Contains(combined, "connection refused") {
		steps = append(steps, "بررسی روشن بودن دیتابیس در کنسول")
		steps = append(steps, "استفاده از Internal Host در شبکه خصوصی لیارا")
		steps = append(steps, "بررسی و تنظیم متغیرهای محیطی دیتابیس")
		return steps
	}

	// 2. Specific Frameworks & Platforms
	if strings.Contains(combined, "next") || strings.Contains(combined, "nextjs") {
		steps = append(steps, "تنظیم output: 'standalone' در next.config.js")
		steps = append(steps, "ساخت فایل liara.json برای Next.js")
		steps = append(steps, "تنظیم متغیرهای محیطی با دستور: liara env:set")
		steps = append(steps, "استقرار با دستور: liara deploy")
		return steps
	}
	if strings.Contains(combined, "laravel") || strings.Contains(combined, "لاراول") {
		steps = append(steps, "تنظیم APP_KEY و متغیرهای دیتابیس در بخش Envs")
		steps = append(steps, "اتصال دیسک پایدار برای پوشه storage")
		steps = append(steps, "اجرای مایگریشن‌ها با دستور: liara run php artisan migrate")
		return steps
	}
	if strings.Contains(combined, "django") || strings.Contains(combined, "جنگو") {
		steps = append(steps, "تنظیم ALLOWED_HOSTS = ['*'] در settings.py")
		steps = append(steps, "تولید requirements.txt با pip freeze")
		steps = append(steps, "اتصال دیسک ابری برای فایل‌های مدیا (/media)")
		return steps
	}
	if strings.Contains(combined, "docker") || strings.Contains(combined, "داکر") {
		steps = append(steps, "ساخت فایل Dockerfile چندمرحله‌ای بهینه")
		steps = append(steps, "تنظیم پورت کانتینر در liara.json")
		steps = append(steps, "تست بیلد محلی داکر قبل از دیپلوی")
		return steps
	}
	if strings.Contains(combined, "node") || strings.Contains(combined, "express") || strings.Contains(combined, "nest") {
		steps = append(steps, "تعریف اسکریپت start در package.json")
		steps = append(steps, "ساخت فایل liara.json برای Node.js")
		steps = append(steps, "تنظیم پورت با متغیر PORT")
		return steps
	}
	if strings.Contains(combined, "go") || strings.Contains(combined, "golang") {
		steps = append(steps, "تنظیم گوش دادن برنامه به پورت 8080")
		steps = append(steps, "بررسی وجود go.mod و وابستگی‌ها")
		steps = append(steps, "استقرار مستقیم با دستور: liara deploy")
		return steps
	}

	// 3. Database Services
	if strings.Contains(combined, "postgres") || strings.Contains(combined, "postgresql") {
		steps = append(steps, "دریافت اطلاعات اتصال (Connection URI) از کنسول")
		steps = append(steps, "اتصال به پایگاه‌داده با هاست داخلی (Internal)")
		steps = append(steps, "پشتیبان‌گیری خودکار دیتابیس در لیارا")
		return steps
	}
	if strings.Contains(combined, "mysql") || strings.Contains(combined, "mariadb") {
		steps = append(steps, "تنظیم متغیرهای DB_HOST, DB_USER, DB_PASSWORD")
		steps = append(steps, "دسترسی به phpMyAdmin داخلی لیارا")
		steps = append(steps, "تنظیم پورت پیش‌فرض 3306")
		return steps
	}
	if strings.Contains(combined, "redis") {
		steps = append(steps, "تنظیم REDIS_HOST و REDIS_PORT در برنامه")
		steps = append(steps, "پیکربندی رمز عبور REDIS_PASSWORD")
		steps = append(steps, "استفاده به عنوان کش و مدیریت Session")
		return steps
	}

	// 4. Disks & Storage
	if strings.Contains(combined, "disk") || strings.Contains(combined, "دیسک") || strings.Contains(combined, "فایل") || strings.Contains(combined, "storage") {
		steps = append(steps, "ایجاد دیسک ابری با دستور: liara disk:create")
		steps = append(steps, "اتصال دیسک در فایل liara.json (mountTo)")
		steps = append(steps, "پشتیبان‌گیری از اطلاعات دیسک در کنسول")
		return steps
	}

	// 5. General Deployment & CLI
	if strings.Contains(combined, "deploy") || strings.Contains(combined, "دیپلوی") || strings.Contains(combined, "استقرار") || strings.Contains(combined, "شروع") {
		steps = append(steps, "ورود به حساب با دستور: liara login")
		steps = append(steps, "ساخت برنامه با دستور: liara app:create")
		steps = append(steps, "استقرار پروژه با دستور: liara deploy")
		steps = append(steps, "مشاهده لاگ‌های زنده با دستور: liara logs --follow")
		return steps
	}

	// Default intelligent suggestions
	steps = append(steps, "مشاهده لاگ‌های لحظه‌ای: liara logs")
	steps = append(steps, "بررسی وضعیت منابع و سلامت: liara status")
	steps = append(steps, "تولید خودکار فایل کانفیگ liara.json")
	return steps
}
